name-template: 'Usaybia.net web application pre-release version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH-dev' # Different config files are referenced by workflows in different branches to allow 'dev' to be prepended only to development releases. See input: config-name in workflow file.
categories:
  - title: '📚 New Content'
    labels:
      - 'changelog: new content'
  - title: '📝 Corrected Content'
    labels:
      - 'changelog: corrected content'
  - title: '📐 Changes to Schema, Standards, or Data Model'
    labels:
      - 'changelog: schema changes'
  - title: '💡 New Features'
    labels:
      - 'changelog: new app features'
  - title: '🐛 Bug Fixes'
    labels:
      - 'changelog: bug fixes'
  - title: '🎛 Visualization Tweaks'
    labels:
      - 'changelog: visualization tweaks'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true # This can also be specified in the workflow file to allow differences between branches
version-resolver:
  major:
    labels:
      - 'changelog: major release'
  minor:
    labels:
      - 'changelog: schema changes'
      - 'changelog: new content'
      - 'changelog: new app features'
  patch:
    labels:
      - 'changelog: bug fixes'
      - 'changelog: visualization tweaks'
      - 'changelog: corrected content'
  default: patch
exclude-labels:
  - 'changelog: ignore'
template: |
  This release is intended for testing the web application used on the [Usaybia.net](https://usaybia.net) website for the project _Communities of Knowledge: Interreligious Networks of Scholars in Ibn Abi Usaybia’s History of the Physicians_ (_Wissensgemeinschaften: interreligiöse Gelehrtennetzwerke in Ibn Abi Usaybiʿa’s Geschichte der Ärzte_). 

  It is intended to be used with data from the [usaybia-data repository](https://github.com/usaybia/usaybia-data).

  The .xar package should be installed in [eXist-db 5.x](http://exist-db.org/exist/apps/homepage/index.html). 

  You can also make your own .xar of the application by downloading this repo and running ant in the repo directory. A docker image of eXist-db with this package pre-installed is available at https://github.com/orgs/usaybia/packages/container/package/usaybia-srophe-exist-app.
  
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS